### ISSUE TITLE
enhancement : buttons that control both deck and note type

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ijgnd/anki21__editor_quick_note_and_deck_buttons#3]
Hi !

I have a note type for adding foreign words, I always add them to the same deck. Do you think it would be possible to allow for buttons that when pressed specify both a deck and a note type ? Currently I have to have two buttons.

Thanks a lot anyway, this already saves me a lot of time

**Comment by ijgnd** [comment]
That sounds useful for some cases.

But I'm afraid that it would be too time consuming to implement this. So I won't do this in the near future.

possible workaround: the deck override option, https://apps.ankiweb.net/docs/manual.html#deckoverride

**Comment by ijgnd** [comment]
The most recent version of "quick note and deck buttons" offers: "when you change a deck (or notetype) you can change the note type (or deck) and tags at the same time". This function is only available for Anki version 2.1.24 or later.

If you run into a problem with this new version please let me know and make a new topic.
