### ISSUE TITLE
Got an error in Anki 2.1.20

### ISSUE THREAD

**Issue by Junyu25** [ijgnd/anki21__editor_quick_note_and_deck_buttons#4]
@ijgnd I really like this addon, but I got an error when I update anki to 2.1.20 version.
Can you help me check it out?

Debug info:
Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-02-22 11:51:02

Caught exception:
Traceback (most recent call last):
  File "C:\Users\*\AppData\Roaming\Anki2\addons21\1331140127\quick_note_deck_buttons.py", line 106, in <lambda>
    l = lambda _=None, s=chooser, nn=button_item["name"]: do_function(
  File "C:\Users\*\AppData\Roaming\Anki2\addons21\1331140127\quick_note_deck_buttons.py", line 149, in change_model_to
    runHook("currentModelChanged")
  File "lib\site-packages\anki\hooks.py", line 475, in runHook
  File "aqt\deckchooser.py", line 72, in onModelChange
  File "aqt\deckchooser.py", line 95, in setDeckName
RuntimeError: wrapped C/C++ object of type QPushButton has been deleted

**Comment by ijgnd** [comment]
update your add-ons try again. It seems that you use an old version of the add-on.

Does the error still occur after updating all add-ons and restarting Anki?

If so: That's bad because I don't get this error. From the main window click on Help->About. In the window that opens click the "Copy Debug Info" Button and share the copied text.

**Comment by Junyu25** [comment]
I already Check for Updates, and I'm sure it's newest version, but the error still exist.
So I just delete and reinstall it and problem solved...
I don't know if it's incompatible with another addon. 
Anyway thank you for your effort in porting this awesome addon.

**Comment by ijgnd** [comment]
I just updated the add-on on ankiweb. Apparently I forgot to upload the most recent changes. Could you update and try again.

And: thanks for the initial report. Otherwise I wouldn't have noticed that there's a problem with the ankiweb listing.
